/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Méda BOUKA
 */
public class GestionEnseignants extends javax.swing.JFrame {

    /**
     * Creates new form GestionEnseignants
     */
    public GestionEnseignants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneANNULE = new javax.swing.JPanel();
        CREATIONENSEIGNAT = new javax.swing.JLabel();
        ENSEIGNANT = new javax.swing.JLabel();
        btnEnregistrer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnAfficher = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        ANNULER = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnRetour = new javax.swing.JButton();
        txtRechercher = new javax.swing.JTextField();
        RECHERCH = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        DATEDARRIVERAUSCHOOL = new javax.swing.JLabel();
        SEX = new javax.swing.JLabel();
        FIRSTNAME = new javax.swing.JLabel();
        txtLieuDeNaissance = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        DATEDENAISS = new javax.swing.JLabel();
        LIEUDENAISS = new javax.swing.JLabel();
        ADRES = new javax.swing.JLabel();
        SITUATIONMATRI = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        NOMBREENFANTENCHARGE = new javax.swing.JLabel();
        NATIONALITY = new javax.swing.JLabel();
        QUATTER = new javax.swing.JLabel();
        txtAdresse = new javax.swing.JTextField();
        txtDateDeNaissance = new javax.swing.JTextField();
        txtNationalite = new javax.swing.JTextField();
        txtStatutMatrimonial = new javax.swing.JTextField();
        txtSexe = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtEnfants = new javax.swing.JTextField();
        txtQuartier = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        TELEPHONE = new javax.swing.JLabel();
        txtCNI = new javax.swing.JTextField();
        txtDateArrivee = new javax.swing.JTextField();
        txtStatut = new javax.swing.JTextField();
        txtProvenance = new javax.swing.JTextField();
        ECOLEDEPROV = new javax.swing.JLabel();
        STATUT = new javax.swing.JLabel();
        CARTENATIONLEDIDENTITE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPaneANNULE.setBackground(new java.awt.Color(255, 51, 51));
        jPaneANNULE.setForeground(new java.awt.Color(255, 51, 51));

        CREATIONENSEIGNAT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CREATIONENSEIGNAT.setText("CREATION ENSEIGNANT");

        ENSEIGNANT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ENSEIGNANT.setText("ENSEIGNANT");

        btnEnregistrer.setText("ENREGISTRER");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("ANNULER");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnAjouter.setText("AJOUTER");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnAfficher.setText("AFFICHER");
        btnAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherActionPerformed(evt);
            }
        });

        btnModifier.setText("MODIFIER");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        ANNULER.setText("ANNULER");

        btnSupprimer.setText("SUPRIMER");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnRetour.setText("RETOUR");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        RECHERCH.setText("RECHERCHER");

        NAME.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NAME.setText("NOM");

        DATEDARRIVERAUSCHOOL.setText("DATE D'ARRIVER A L'ECOLE");

        SEX.setText("SEXE");

        FIRSTNAME.setText("PRENOM");

        txtLieuDeNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLieuDeNaissanceActionPerformed(evt);
            }
        });

        DATEDENAISS.setText("DATE DE NAISSANCE");

        LIEUDENAISS.setText("LIEU DE NAISSANCE ");

        ADRES.setText("ADRRESSE");

        SITUATIONMATRI.setText("SITUATION MATRIMONIALE");

        EMAIL.setText("Email");

        NOMBREENFANTENCHARGE.setText("NOMBRE D'ENFANTS EN CHARGE");

        NATIONALITY.setText("NATIONALITE");

        QUATTER.setText("QUARTIER");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        TELEPHONE.setText("TELEPHONE");

        txtStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatutActionPerformed(evt);
            }
        });

        ECOLEDEPROV.setText("ECOLE DE PROVENANCE");

        STATUT.setText("STATUT");

        CARTENATIONLEDIDENTITE.setText("CNI");

        javax.swing.GroupLayout jPaneANNULELayout = new javax.swing.GroupLayout(jPaneANNULE);
        jPaneANNULE.setLayout(jPaneANNULELayout);
        jPaneANNULELayout.setHorizontalGroup(
            jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneANNULELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAfficher)
                            .addComponent(btnAjouter))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneANNULELayout.createSequentialGroup()
                                .addComponent(btnEnregistrer)
                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneANNULELayout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(ADRES))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneANNULELayout.createSequentialGroup()
                                                .addGap(113, 113, 113)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel14)
                                        .addGap(423, 423, 423))
                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                .addGap(109, 109, 109)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(SEX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(DATEDENAISS)
                                                            .addComponent(txtDateDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 127, Short.MAX_VALUE)))))
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                .addGap(227, 227, 227)
                                                .addComponent(txtNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                                        .addComponent(NATIONALITY)
                                                        .addGap(9, 9, 9))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(FIRSTNAME))
                                                        .addGap(26, 26, 26))))
                                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LIEUDENAISS)
                                                    .addComponent(txtLieuDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(56, 56, 56))))
                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                        .addComponent(RECHERCH, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnModifier, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ANNULER, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRetour)
                                            .addComponent(btnSupprimer)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                        .addComponent(CREATIONENSEIGNAT, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ENSEIGNANT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NOMBREENFANTENCHARGE)
                                            .addComponent(txtEnfants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(DATEDARRIVERAUSCHOOL, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtDateArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(11, 11, 11))))
                            .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                    .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPaneANNULELayout.createSequentialGroup()
                                            .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtStatutMatrimonial, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(SITUATIONMATRI)
                                                .addComponent(ECOLEDEPROV)
                                                .addComponent(txtProvenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                    .addGap(349, 349, 349)
                                                    .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(QUATTER)
                                                        .addComponent(txtQuartier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TELEPHONE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                                    .addGap(14, 14, 14)
                                                    .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCNI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(CARTENATIONLEDIDENTITE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(10, 10, 10))))
                                        .addGroup(jPaneANNULELayout.createSequentialGroup()
                                            .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)))
                                    .addGap(56, 56, 56))
                                .addGroup(jPaneANNULELayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(STATUT)
                                        .addComponent(txtStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(438, 438, 438))))
                        .addContainerGap())))
        );
        jPaneANNULELayout.setVerticalGroup(
            jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneANNULELayout.createSequentialGroup()
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CREATIONENSEIGNAT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ENSEIGNANT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIRSTNAME)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addComponent(DATEDENAISS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDateDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NATIONALITY)
                            .addComponent(SEX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNationalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addComponent(LIEUDENAISS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLieuDeNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(SITUATIONMATRI))
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(txtStatutMatrimonial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addComponent(NOMBREENFANTENCHARGE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEnfants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(QUATTER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuartier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel14))
                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(ADRES)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TELEPHONE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                        .addComponent(EMAIL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                        .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DATEDARRIVERAUSCHOOL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(STATUT))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtDateArrivee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CARTENATIONLEDIDENTITE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECOLEDEPROV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(txtProvenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEnregistrer)
                        .addComponent(RECHERCH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAnnuler, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnModifier)
                    .addComponent(btnSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfficher)
                    .addComponent(ANNULER)
                    .addComponent(btnRetour))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneANNULE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneANNULE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatutActionPerformed

    private void txtLieuDeNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLieuDeNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLieuDeNaissanceActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        String nom = txtNom.getText();
        String prenom = txtPrenom.getText();
        String adresse = txtAdresse.getText();
        String email = txtEmail.getText();
        String sexe = txtSexe.getText();
        String cni = txtCNI.getText();
        String telephone = txtTelephone.getText();
        String dateArrivee = txtDateArrivee.getText();
        String statutMatrimonial = txtStatutMatrimonial.getText();
        String enfants = txtEnfants.getText();
        String quartier = txtQuartier.getText();
        String statut = txtStatut.getText();
        String naissance = txtDateDeNaissance.getText();
        String lieuDeNaissance = txtLieuDeNaissance.getText();
        String nationalite = txtNationalite.getText();
        String provenance = txtProvenance.getText();
        
          String query = "INSERT INTO enseignants (nom, prenom, date_de_naissance, lieu_de_naissance, sexe, nationalite,situation_matrimonial,adresse,quartier,email,telephone,statut,arrive,provenance,cni,enfants) "
                  + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
          PreparedStatement
          
        



    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btnRetourActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAfficherActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEnseignants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEnseignants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEnseignants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEnseignants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionEnseignants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADRES;
    private javax.swing.JButton ANNULER;
    private javax.swing.JLabel CARTENATIONLEDIDENTITE;
    private javax.swing.JLabel CREATIONENSEIGNAT;
    private javax.swing.JLabel DATEDARRIVERAUSCHOOL;
    private javax.swing.JLabel DATEDENAISS;
    private javax.swing.JLabel ECOLEDEPROV;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JLabel ENSEIGNANT;
    private javax.swing.JLabel FIRSTNAME;
    private javax.swing.JLabel LIEUDENAISS;
    private javax.swing.JLabel NAME;
    private javax.swing.JLabel NATIONALITY;
    private javax.swing.JLabel NOMBREENFANTENCHARGE;
    private javax.swing.JLabel QUATTER;
    private javax.swing.JLabel RECHERCH;
    private javax.swing.JLabel SEX;
    private javax.swing.JLabel SITUATIONMATRI;
    private javax.swing.JLabel STATUT;
    private javax.swing.JLabel TELEPHONE;
    private javax.swing.JButton btnAfficher;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPaneANNULE;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCNI;
    private javax.swing.JTextField txtDateArrivee;
    private javax.swing.JTextField txtDateDeNaissance;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnfants;
    private javax.swing.JTextField txtLieuDeNaissance;
    private javax.swing.JTextField txtNationalite;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtProvenance;
    private javax.swing.JTextField txtQuartier;
    private javax.swing.JTextField txtRechercher;
    private javax.swing.JTextField txtSexe;
    private javax.swing.JTextField txtStatut;
    private javax.swing.JTextField txtStatutMatrimonial;
    private javax.swing.JTextField txtTelephone;
    // End of variables declaration//GEN-END:variables
}
