/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Méda BOUKA
 */
public class GESTIONDESENSEIGNANTS extends javax.swing.JFrame {

    /**
     * Creates new form GESTIONDESENSEIGNANTS
     */
    public GESTIONDESENSEIGNANTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneANNULE = new javax.swing.JPanel();
        CREATIONENSEIGNAT = new javax.swing.JLabel();
        ENSEIGNANT = new javax.swing.JLabel();
        ENREGISTRER = new javax.swing.JButton();
        ANNULE = new javax.swing.JButton();
        AJOUTER = new javax.swing.JButton();
        AFFICHER = new javax.swing.JButton();
        MODIFIER = new javax.swing.JButton();
        ANNULER = new javax.swing.JButton();
        SUPPRIMER = new javax.swing.JButton();
        RETOUR = new javax.swing.JButton();
        RECHERCHER = new javax.swing.JTextField();
        RECHERCH = new javax.swing.JLabel();
        NAME = new javax.swing.JLabel();
        DATEDARRIVERAUSCHOOL = new javax.swing.JLabel();
        SEX = new javax.swing.JLabel();
        FIRSTNAME = new javax.swing.JLabel();
        LIEUDENAISSANCE = new javax.swing.JTextField();
        PRENOM = new javax.swing.JTextField();
        NOM = new javax.swing.JTextField();
        DATEDENAISS = new javax.swing.JLabel();
        LIEUDENAISS = new javax.swing.JLabel();
        ADRES = new javax.swing.JLabel();
        SITUATIONMATRI = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();
        NOMBREENFANTENCHARGE = new javax.swing.JLabel();
        NATIONALITY = new javax.swing.JLabel();
        QUATTER = new javax.swing.JLabel();
        ADRESSE = new javax.swing.JTextField();
        DATEDENAISSANCE = new javax.swing.JTextField();
        NATIONALITA = new javax.swing.JTextField();
        SITUATIONMATRIMONIAL = new javax.swing.JTextField();
        SEXE = new javax.swing.JTextField();
        eMAIL = new javax.swing.JTextField();
        NOMBREDENFANTENCHARGE = new javax.swing.JTextField();
        QUARTIER = new javax.swing.JTextField();
        TTELEPHONNE = new javax.swing.JTextField();
        TELEPHONE = new javax.swing.JLabel();
        CNI = new javax.swing.JTextField();
        DATEDARRIVERALECOLE = new javax.swing.JTextField();
        statut = new javax.swing.JTextField();
        ECOLEDEPROVENANCE = new javax.swing.JTextField();
        ECOLEDEPROV = new javax.swing.JLabel();
        STATUT = new javax.swing.JLabel();
        CARTENATIONLEDIDENTITE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPaneANNULE.setBackground(new java.awt.Color(255, 51, 51));
        jPaneANNULE.setForeground(new java.awt.Color(255, 51, 51));

        CREATIONENSEIGNAT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CREATIONENSEIGNAT.setText("CREATION ENSEIGNANT");

        ENSEIGNANT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ENSEIGNANT.setText("ENSEIGNANT");

        ENREGISTRER.setText("ENREGISTRER");

        ANNULE.setText("ANNULER");

        AJOUTER.setText("AJOUTER");

        AFFICHER.setText("AFFICHER");

        MODIFIER.setText("MODIFIER");

        ANNULER.setText("ANNULER");

        SUPPRIMER.setText("SUPRIMER");

        RETOUR.setText("RETOUR");

        RECHERCHER.setText("RECHERCHER");

        RECHERCH.setText("RECHERCHER");

        NAME.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        NAME.setText("NOM");

        DATEDARRIVERAUSCHOOL.setText("DATE D'ARRIVER A L'ECOLE");

        SEX.setText("SEXE");

        FIRSTNAME.setText("PRENOM");

        LIEUDENAISSANCE.setText("LIEU DE NAISSANCE");

        PRENOM.setText("PRENOM");

        NOM.setText("NOM");

        DATEDENAISS.setText("DATE DE NAISSANCE");

        LIEUDENAISS.setText("LIEU DE NAISSANCE ");

        ADRES.setText("ADRRESSE");

        SITUATIONMATRI.setText("SITUATION MATRIMONIALE");

        EMAIL.setText("Email");

        NOMBREENFANTENCHARGE.setText("NOMBRE D'ENFANTS EN CHARGE");

        NATIONALITY.setText("NATIONALITE");

        QUATTER.setText("QUARTIER");

        ADRESSE.setText("ADRESSE");

        DATEDENAISSANCE.setText("DATE DE NAISSANCE");

        NATIONALITA.setText("NATIONALITE");

        SITUATIONMATRIMONIAL.setText("SITUATION MATRIMONIALE");

        SEXE.setText("SEXE");

        eMAIL.setText("Email");
        eMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMAILActionPerformed(evt);
            }
        });

        NOMBREDENFANTENCHARGE.setText("NOMBRE D'ENFANTS EN CHARGE");

        QUARTIER.setText("QUARTIER");

        TTELEPHONNE.setText("TELEPHONE");

        TELEPHONE.setText("TELEPHONE");

        CNI.setText("CNI");

        DATEDARRIVERALECOLE.setText("DATE D'ARRIVER A L'ECOLE");

        statut.setText("STATUT");
        statut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statutActionPerformed(evt);
            }
        });

        ECOLEDEPROVENANCE.setText("ECOLE DE PROVENANCE");

        ECOLEDEPROV.setText("ECOLE DE PROVENANCE");

        STATUT.setText("STATUT");

        CARTENATIONLEDIDENTITE.setText("CNI");

        javax.swing.GroupLayout jPaneANNULELayout = new javax.swing.GroupLayout(jPaneANNULE);
        jPaneANNULE.setLayout(jPaneANNULELayout);
        jPaneANNULELayout.setHorizontalGroup(
            jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneANNULELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AFFICHER)
                            .addComponent(AJOUTER))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneANNULELayout.createSequentialGroup()
                                .addComponent(ENREGISTRER)
                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneANNULELayout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(ADRES))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPaneANNULELayout.createSequentialGroup()
                                                .addGap(113, 113, 113)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(ADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(eMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel14)
                                        .addGap(423, 423, 423))
                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                .addGap(109, 109, 109)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(NOM, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(DATEDENAISS)
                                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                        .addComponent(DATEDENAISSANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 127, Short.MAX_VALUE))
                                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(SEXE, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(SEX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                .addGap(227, 227, 227)
                                                .addComponent(NATIONALITA, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                                        .addComponent(NATIONALITY)
                                                        .addGap(9, 9, 9))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(PRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(FIRSTNAME))
                                                        .addGap(26, 26, 26))))
                                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LIEUDENAISS)
                                                    .addComponent(LIEUDENAISSANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(56, 56, 56))))
                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                        .addComponent(RECHERCH, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MODIFIER, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ANNULER, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RECHERCHER, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RETOUR)
                                            .addComponent(SUPPRIMER)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                        .addComponent(CREATIONENSEIGNAT, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ENSEIGNANT, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NOMBREENFANTENCHARGE)
                                            .addComponent(NOMBREDENFANTENCHARGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(DATEDARRIVERAUSCHOOL, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(DATEDARRIVERALECOLE, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(11, 11, 11))))
                            .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                    .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPaneANNULELayout.createSequentialGroup()
                                            .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(SITUATIONMATRIMONIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(SITUATIONMATRI)
                                                .addComponent(ECOLEDEPROV)
                                                .addComponent(ECOLEDEPROVENANCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ANNULE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPaneANNULELayout.createSequentialGroup()
                                                    .addGap(349, 349, 349)
                                                    .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(QUATTER)
                                                        .addComponent(QUARTIER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TELEPHONE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                                                    .addGap(14, 14, 14)
                                                    .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(CNI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(CARTENATIONLEDIDENTITE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(10, 10, 10))))
                                        .addGroup(jPaneANNULELayout.createSequentialGroup()
                                            .addComponent(TTELEPHONNE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1)))
                                    .addGap(56, 56, 56))
                                .addGroup(jPaneANNULELayout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(STATUT)
                                        .addComponent(statut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(438, 438, 438))))
                        .addContainerGap())))
        );
        jPaneANNULELayout.setVerticalGroup(
            jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneANNULELayout.createSequentialGroup()
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CREATIONENSEIGNAT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ENSEIGNANT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIRSTNAME)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRENOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addComponent(DATEDENAISS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DATEDENAISSANCE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NATIONALITY)
                            .addComponent(SEX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NATIONALITA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SEXE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addComponent(LIEUDENAISS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LIEUDENAISSANCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(SITUATIONMATRI))
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(SITUATIONMATRIMONIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addComponent(NOMBREENFANTENCHARGE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NOMBREDENFANTENCHARGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(QUATTER)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QUARTIER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                        .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel14))
                            .addGroup(jPaneANNULELayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(ADRES)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ADRESSE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TELEPHONE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                        .addComponent(EMAIL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPaneANNULELayout.createSequentialGroup()
                                        .addComponent(TTELEPHONNE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DATEDARRIVERAUSCHOOL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(STATUT))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(DATEDARRIVERALECOLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CARTENATIONLEDIDENTITE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ECOLEDEPROV, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(ECOLEDEPROVENANCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RECHERCHER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ENREGISTRER)
                        .addComponent(RECHERCH, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ANNULE, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AJOUTER)
                    .addComponent(MODIFIER)
                    .addComponent(SUPPRIMER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneANNULELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AFFICHER)
                    .addComponent(ANNULER)
                    .addComponent(RETOUR))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPaneANNULE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPaneANNULE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMAILActionPerformed

    private void statutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GESTIONDESENSEIGNANTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GESTIONDESENSEIGNANTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GESTIONDESENSEIGNANTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GESTIONDESENSEIGNANTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GESTIONDESENSEIGNANTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADRES;
    private javax.swing.JTextField ADRESSE;
    private javax.swing.JButton AFFICHER;
    private javax.swing.JButton AJOUTER;
    private javax.swing.JButton ANNULE;
    private javax.swing.JButton ANNULER;
    private javax.swing.JLabel CARTENATIONLEDIDENTITE;
    private javax.swing.JTextField CNI;
    private javax.swing.JLabel CREATIONENSEIGNAT;
    private javax.swing.JTextField DATEDARRIVERALECOLE;
    private javax.swing.JLabel DATEDARRIVERAUSCHOOL;
    private javax.swing.JLabel DATEDENAISS;
    private javax.swing.JTextField DATEDENAISSANCE;
    private javax.swing.JLabel ECOLEDEPROV;
    private javax.swing.JTextField ECOLEDEPROVENANCE;
    private javax.swing.JLabel EMAIL;
    private javax.swing.JButton ENREGISTRER;
    private javax.swing.JLabel ENSEIGNANT;
    private javax.swing.JLabel FIRSTNAME;
    private javax.swing.JLabel LIEUDENAISS;
    private javax.swing.JTextField LIEUDENAISSANCE;
    private javax.swing.JButton MODIFIER;
    private javax.swing.JLabel NAME;
    private javax.swing.JTextField NATIONALITA;
    private javax.swing.JLabel NATIONALITY;
    private javax.swing.JTextField NOM;
    private javax.swing.JTextField NOMBREDENFANTENCHARGE;
    private javax.swing.JLabel NOMBREENFANTENCHARGE;
    private javax.swing.JTextField PRENOM;
    private javax.swing.JTextField QUARTIER;
    private javax.swing.JLabel QUATTER;
    private javax.swing.JLabel RECHERCH;
    private javax.swing.JTextField RECHERCHER;
    private javax.swing.JButton RETOUR;
    private javax.swing.JLabel SEX;
    private javax.swing.JTextField SEXE;
    private javax.swing.JLabel SITUATIONMATRI;
    private javax.swing.JTextField SITUATIONMATRIMONIAL;
    private javax.swing.JLabel STATUT;
    private javax.swing.JButton SUPPRIMER;
    private javax.swing.JLabel TELEPHONE;
    private javax.swing.JTextField TTELEPHONNE;
    private javax.swing.JTextField eMAIL;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPaneANNULE;
    private javax.swing.JTextField statut;
    // End of variables declaration//GEN-END:variables
}
